language: scala

scala:
    - 2.11.6

before_script:
    - sbt clean

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/083ad9d705807e5836a2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false